name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer dependencies
        run: |
          sudo apt update --fix-missing
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev || sudo apt install -f
          pip install --upgrade pip
          pip install buildozer
          pip install cython

      - name: Build APK
        run: |
          ls -la my_kivy_app
          buildozer -v android debug --directory my_kivy_app
          
          sed -i 's/android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
          sed -i 's/android.enforce_sdk_license = True/android.enforce_sdk_license = False/' buildozer.spec
          sed -i 's/android.enforce_android_license = True/android.enforce_android_license = False/' buildozer.spec
          
          sed -i 's/android.sdk_version = [0-9]*/android.sdk_version = 33/' buildozer.spec
          sed -i 's/android.ndk_version = [0-9a-z.]*/android.ndk_version = 23b/' buildozer.spec
          # 设置包名
          sed -i 's/package.name = .*/package.name = myapp/' buildozer.spec
          sed -i 's/package.domain = .*/package.domain = org.myapp/' buildozer.spec
          # 执行打包
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp
          path: bin/*.apk
